version: "3.9"

services:
  billy-h-scraper:
    container_name: billy-h-scraper
    image: fajfer/billy-h-scraper:latest
    build: .
    restart: unless-stopped
    environment: # example
      # Mandatory variables for both Telegram and Discord
      - MSG_DELAY=60
      - WEB_URL=https://wp.pl
      # Telegram variables
      - GROUPS=@wp_pl,10101010,@global_news
      - BOT_TOKEN=000000:AAAAAABBBBBBCCCCCCC
      # Discord variables
      - WEBHOOKS=https://discord.com/api/webhooks/.../...,https://discord.com/api/webhooks/.../...
      # - AVATAR_URL=  # Optional webhook avatar URL
    volumes:
      - ./history:/app/history
